### ISSUE TITLE
Update docs to specify this verison only works with jogl pre 2.3

### ISSUE THREAD

**Issue by sgwilbur** [battlecode/battlecode-client#7]
The javax.media.* has been refactored to com.jogamp.*
http://jogamp.org/git/?p=jogl.git;a=commit;h=1ec82447e464d5308442581f14d32f9775928454

Otherwise you will see these errors building the client with 2.3 or current:

    Buildfile: /Volumes/melange/workspaces/battlecode/battlecode-client/build.xml

    init:

    compile:
        [javac] Compiling 63 source files to /Volumes/melange/workspaces/battlecode/battlecode-client/build/classes
        [javac] warning: [options] bootstrap class path not set in conjunction with -source 1.7
        [javac] /Volumes/melange/workspaces/battlecode/battlecode-client/src/main/battlecode/client/viewer/AbstractAnimation.java:4: error: package javax.media.opengl does not exist
        [javac] import javax.media.opengl.GL;
        [javac]                          ^
        [javac] /Volumes/melange/workspaces/battlecode/battlecode-client/src/main/battlecode/client/viewer/AbstractAnimation.java:5: error: package javax.media.opengl.glu does not exist
        [javac] import javax.media.opengl.glu.GLU;
        [javac]                              ^
        [javac] /Volumes/melange/workspaces/battlecode/battlecode-client/src/main/battlecode/client/util/OBJFile.java:18: error: package javax.media.opengl does not exist
        [javac] import javax.media.opengl.GL;
        [javac]                          ^
        [javac] /Volumes/melange/workspaces/battlecode/battlecode-client/src/main/battlecode/client/util/OBJFile.java:19: error: package javax.media.opengl does not exist
        [javac] import javax.media.opengl.GL2;
        [javac]                          ^
        [javac] /Volumes/melange/workspaces/battlecode/battlecode-client/src/main/battlecode/client/util/OBJFile.java:275: error: cannot find symbol
        [javac]     public void draw(GL2 gl) {
        [javac]                      ^
        [javac]   symbol:   class GL2
        [javac]   location: class OBJFile
        [javac] /Volumes/melange/workspaces/battlecode/battlecode-client/src/main/battlecode/client/MatchDialog.java:292: warning: [unchecked] unchecked call to JList(ListModel<E>) as a member of the raw type JList
        [javac]         lstMatches = new JList(lstMatchesModel);
        [javac]                      ^
        [javac]   where E is a type-variable:
        [javac]     E extends Object declared in class JList
        [javac] /Volumes/melange/workspaces/battlecode/battlecode-client/src/main/battlecode/client/MatchDialog.java:394: warning: [unchecked] unchecked call to addElement(E) as a member of the raw type DefaultListModel
        [javac]                 lstMatchesModel.addElement(mapName);
        [javac]                                           ^
        [javac]   where E is a type-variable:
        [javac]     E extends Object declared in class DefaultListModel
        [javac] /Volumes/melange/workspaces/battlecode/battlecode-client/src/main/battlecode/client/MatchDialog.java:583: warning: [unchecked] unchecked call to addElement(E) as a member of the raw type DefaultListModel
        [javac]             lstMatchesModel.addElement(map);
        [javac]                                       ^
        [javac]   where E is a type-variable:
        [javac]     E extends Object declared in class DefaultListModel
        [javac] /Volumes/melange/workspaces/battlecode/battlecode-client/src/main/battlecode/client/MatchDialog.java:622: warning: [unchecked] unchecked call to addItem(E) as a member of the raw type JComboBox
        [javac]                 parameters.get(Parameter.TEAM_A).addItem(s);
        [javac]                                                         ^
        [javac]   where E is a type-variable:
        [javac]     E extends Object declared in class JComboBox
        [javac] /Volumes/melange/workspaces/battlecode/battlecode-client/src/main/battlecode/client/MatchDialog.java:623: warning: [unchecked] unchecked call to addItem(E) as a member of the raw type JComboBox
        [javac]                 parameters.get(Parameter.TEAM_B).addItem(s);
        [javac]                                                         ^
        [javac]   where E is a type-variable:
        [javac]     E extends Object declared in class JComboBox
        [javac] /Volumes/melange/workspaces/battlecode/battlecode-client/src/main/battlecode/client/MatchDialog.java:631: warning: [unchecked] unchecked call to addItem(E) as a member of the raw type JComboBox
        [javac]                 parameters.get(Parameter.MAP).addItem(s);
        [javac]                                                      ^
        [javac]   where E is a type-variable:
        [javac]     E extends Object declared in class JComboBox
        [javac] /Volumes/melange/workspaces/battlecode/battlecode-client/src/main/battlecode/client/viewer/AbstractDrawState.java:424: warning: [unchecked] unchecked call to setSupplyTransfer(AbstractDrawObject<Animation>,double) as a member of the raw type AbstractDrawObject
        [javac]     from.setSupplyTransfer(to,s.amount);
        [javac]                           ^
        [javac]   where Animation is a type-variable:
        [javac]     Animation extends AbstractAnimation declared in class AbstractDrawObject
        [javac] /Volumes/melange/workspaces/battlecode/battlecode-client/src/main/battlecode/client/util/OBJFile.java:277: error: cannot find symbol
        [javac]         gl.glEnableClientState(GL2.GL_VERTEX_ARRAY);
        [javac]                                ^
        [javac]   symbol:   variable GL2
        [javac]   location: class OBJFile
        [javac] /Volumes/melange/workspaces/battlecode/battlecode-client/src/main/battlecode/client/util/OBJFile.java:278: error: cannot find symbol
        [javac]         gl.glEnableClientState(GL2.GL_NORMAL_ARRAY);
        [javac]                                ^
        [javac]   symbol:   variable GL2
        [javac]   location: class OBJFile
        [javac] /Volumes/melange/workspaces/battlecode/battlecode-client/src/main/battlecode/client/util/OBJFile.java:279: error: cannot find symbol
        [javac]         gl.glEnableClientState(GL2.GL_TEXTURE_COORD_ARRAY);
        [javac]                                ^
        [javac]   symbol:   variable GL2
        [javac]   location: class OBJFile
        [javac] /Volumes/melange/workspaces/battlecode/battlecode-client/src/main/battlecode/client/util/OBJFile.java:281: error: cannot find symbol
        [javac]         gl.glVertexPointer(3, GL2.GL_FLOAT, 0, vBuf);
        [javac]                               ^
        [javac]   symbol:   variable GL2
        [javac]   location: class OBJFile
        [javac] /Volumes/melange/workspaces/battlecode/battlecode-client/src/main/battlecode/client/util/OBJFile.java:282: error: cannot find symbol
        [javac]         gl.glNormalPointer(GL2.GL_FLOAT, 0, nBuf);
        [javac]                            ^
        [javac]   symbol:   variable GL2
        [javac]   location: class OBJFile
        [javac] /Volumes/melange/workspaces/battlecode/battlecode-client/src/main/battlecode/client/util/OBJFile.java:283: error: cannot find symbol
        [javac]         gl.glTexCoordPointer(2, GL2.GL_FLOAT, 0, tBuf);
        [javac]                                 ^
        [javac]   symbol:   variable GL2
        [javac]   location: class OBJFile
        [javac] /Volumes/melange/workspaces/battlecode/battlecode-client/src/main/battlecode/client/util/OBJFile.java:285: error: cannot find symbol
        [javac]         gl.glDrawElements(GL2.GL_TRIANGLES, indexLength, GL2.GL_UNSIGNED_INT, iBuf);
        [javac]                           ^
        [javac]   symbol:   variable GL2
        [javac]   location: class OBJFile
        [javac] /Volumes/melange/workspaces/battlecode/battlecode-client/src/main/battlecode/client/util/OBJFile.java:285: error: cannot find symbol
        [javac]         gl.glDrawElements(GL2.GL_TRIANGLES, indexLength, GL2.GL_UNSIGNED_INT, iBuf);
        [javac]                                                          ^
        [javac]   symbol:   variable GL2
        [javac]   location: class OBJFile
        [javac] /Volumes/melange/workspaces/battlecode/battlecode-client/src/main/battlecode/client/util/OBJFile.java:287: error: cannot find symbol
        [javac]         gl.glDisableClientState(GL2.GL_VERTEX_ARRAY);
        [javac]                                 ^
        [javac]   symbol:   variable GL2
        [javac]   location: class OBJFile
        [javac] /Volumes/melange/workspaces/battlecode/battlecode-client/src/main/battlecode/client/util/OBJFile.java:288: error: cannot find symbol
        [javac]         gl.glDisableClientState(GL2.GL_NORMAL_ARRAY);
        [javac]                                 ^
        [javac]   symbol:   variable GL2
        [javac]   location: class OBJFile
        [javac] /Volumes/melange/workspaces/battlecode/battlecode-client/src/main/battlecode/client/util/OBJFile.java:289: error: cannot find symbol
        [javac]         gl.glDisableClientState(GL2.GL_TEXTURE_COORD_ARRAY);
        [javac]                                 ^
        [javac]   symbol:   variable GL2
        [javac]   location: class OBJFile
        [javac] /Volumes/melange/workspaces/battlecode/battlecode-client/src/main/battlecode/client/viewer/render/GameRenderer.java:219: warning: [unchecked] getRobotByID(int) in GameRenderer overrides getRobotByID(int) in BaseRenderer
        [javac]   public AbstractDrawObject getRobotByID(int id) {
        [javac]                             ^
        [javac]   return type requires unchecked conversion from AbstractDrawObject to AbstractDrawObject<AbstractAnimation>
        [javac] /Volumes/melange/workspaces/battlecode/battlecode-client/src/main/battlecode/client/viewer/render/GameCanvas.java:70: warning: [unchecked] getRobotByID(int) in GameRenderer overrides getRobotByID(int) in BaseRenderer
        [javac]     public final BaseRenderer bracketRenderer = new GameRenderer() {
        [javac]                                                                    ^
        [javac]   return type requires unchecked conversion from AbstractDrawObject to AbstractDrawObject<AbstractAnimation>
        [javac] 16 errors
        [javac] 10 warnings

    BUILD FAILED
    /Volumes/melange/workspaces/battlecode/battlecode-client/build.xml:120: Compile failed; see the compiler error output for details.

**Comment by kazimuth** [comment]
We don't use JOGL anymore.
